# Generated by Django 5.0.4 on 2024-04-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('surname', models.CharField(max_length=50, verbose_name='surname')),
                ('login', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True, verbose_name='login')),
                ('password', models.CharField(max_length=200, verbose_name='password')),
                ('appel', models.TextField(default=' ', verbose_name='appel')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
